spring.application.name=airline-management

spring.datasource.url=jdbc:mysql://localhost:3306/airline_management?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=airlineuser
spring.datasource.password=airline@2026
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

server.port=8081

jwt.secret=5367566859703373367639792F423F4528482B4D6251655468576D5A7134743777217A25432A462D4A614E645267556B58703273357638792F423F4528482B4D
jwt.expiration=86400000